 name: README build

 on:
   push:
     branches:
       - master
   schedule:
     - cron: "0 11 * * *"

 env:
   NODE_VERSION: 14
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout current repository to Master branch
         uses: actions/checkout@v2
       - name: Setup NodeJs 14.x
         uses: actions/setup-node@v1
         with:
           node-version: ${{ env.NODE_VERSION }}
       - name: Cache dependencies and build outputs to improve workflow execution time.
         uses: actions/cache@v1
         with:
           path: node_modules
           key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
       - name: Install dependencies
         run: npm install
       - name: Generate README file
         run: |-
           tsnode src/index.ts
           cat README.md
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Commit and Push new README.md to the repository
#         uses: mikeal/publish-to-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Commit and push if changed
         run: |-
           git add .
           git diff
           git config --global user.email "github-action-bot@example.com"
           git config --global user.name "GitHub Action Bot"
           git commit -m "Updated README" -a || echo "No changes to commit"
           git push