 name: README build

 permissions:
   actions: none
   checks: none
   contents: write
   deployments: read
   issues: read
   packages: read
   pull-requests: read
   repository-projects: read
   security-events: none
   statuses: none

 on:
   pull_request:
   push:
     branches:
       - master
   schedule:
     - cron: "0 11 * * *"

 env:
   NODE_VERSION: 18
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout current repository to Master branch
         uses: actions/checkout@v2
       - name: Setup NodeJs 18.x
         uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODE_VERSION }}
       - name: Cache dependencies and build outputs to improve workflow execution time.
         uses: actions/cache@v3
         with:
           path: node_modules
           key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
       - name: Install dependencies
         run: npm install
       - name: Generate README file
         run: |-
           npm run build
           cat README.md
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       - name: Commit and push if changed
         run: |-
           git add .
           git diff
           git config --global user.email "github-action-bot@example.com"
           git config --global user.name "GitHub Action Bot"
           git commit -m "Updated README" -a || echo "No changes to commit"
           git push